package com.springboot.jpa.hibernate.model;

public enum TownShipAndDistrict {
	BAGO, BAWLAKHE, BHAMO, BOKYIN, DAWEI, DEKKHINA, DEMOSO, FALAM, GANGAW, HAKHA, HINTHADA, HKAMTI, HOPANG,
	WASELF_ADMINISTEREDDIVISION, HPA_AN, KALE, KANBALU, KATHA, KAWKAREIK, KAWLIN, KAWTHAUNG, KENGTUNG, KUNLONG, KYAUKME,
	KYAUKPYU, KYAUKSE, KYONPYAW, LABUTTA, NAGASELF_ADMINISTEREDZONE, LANGHKO, LASHIO, KOKANGSELF_ADMINISTEREDZONE,
	LAUKKAING, LOIKAW, LOILEN, MA_UBIN, MAGWAY, MANDALAY, MATMAN, MATUPI, MAUNGDAW, MAWLAIK, MAWLAMYINE, MEIKTILA, MESE,
	MINBU, MINDAT, MOHNYIN, MONGMIT, MONGHPAYAK, MONGHSAT, MONYWA, MRAUK_U, MUSE, MYANAUNG, MYAUNGMYA, MYAWADDY, MYEIK,
	MYINGYAN, MYITKYINA, NYAUNG_U, OTTARA, PAKOKKU, HPAPUN, PATHEIN, PUTAO, PYAPON, PYAY, PYINOOLWIN, SAGAING, SHWEBO,
	SITTWE, TACHILEIK, TAMU, TAUNGGYI, TAUNGOO, THANDWE, THARRAWADDY, THATON, THAYET, YAMETHIN, EASTYANGON, YINMABIN;

}
